### ISSUE TITLE
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1011831).

### ISSUE THREAD

**Issue by NicolaRedTurtle** [italia/pa-website-validator#91]
Ciao, ho provato a lanciare un test su Mac, OS Monterey vers. 12.6, ottengo questo errore:

Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1011831).
    at ChromeLauncher.launch (file:///private/var/folders/n6/4zy2fkzs4rq35z_6fcktpr8r0000gn/T/caxa/applications/app-valutazione-comuni/drhnsla8w7/0/node_modules/puppeteer/lib/esm/puppeteer/node/ChromeLauncher.js:64:23)
    at async run (file:///private/var/folders/n6/4zy2fkzs4rq35z_6fcktpr8r0000gn/T/caxa/applications/app-valutazione-comuni/drhnsla8w7/0/dist/controller/launchLighthouse.js:21:21)
    at async file:///private/var/folders/n6/4zy2fkzs4rq35z_6fcktpr8r0000gn/T/caxa/applications/app-valutazione-comuni/drhnsla8w7/0/dist/app.js:41:5

La vers. 1.0.9 girava

**Comment by tensor5** [comment]
Ciao @NicolaRedTurtle, grazie mille per la segnalazione. Il problema era nel build del pacchetto per Apple M1 (l'unico che viene fatto a mano). Riscaricalo e funzionerà.

**Comment by NicolaRedTurtle** [comment]
Ciao @tensor5, perfetto. Ti confermo che ora ha ripreso a funzionare.
Grazie a te!
